import LegalLayout from "@/components/layout/LegalLayout";

export default function PrivacyPage() {
    return (
        <LegalLayout title="Política de Privacidad">
            <p>A continuación se detalla cada parte de la política de privacidad de Technologyreview.com, la página de Technology Review, Inc. Esta política fue actualizada el 16 enero de 2007. Preguntas sobre esta política pueden enviarse a customerservice@technologyreview.com. Toda la información recolectada en esta página pertenece únicamente a Technology Review, Inc., y es administrada según lo acordado en esta política.</p>

            <h2>Cómo Reunimos Información</h2>
            <ol>
                <li><strong>Inscripción a MyTechnologyReview.com, Inscripción Online, Subscripciones a la edición impresa, Inscripción a Eventos y a Newsletter:</strong> Para acceder a ciertas áreas de esta página, un usuario debe completar el formulario de inscripción primero. Durante la inscripción, se requerirá que el usuario provea información de contacto (tales como nombre, dirección de e-mail, código postal, País, Trabajo, Puesto/Función e Industria). Las direcciones de e-mail son utilizadas para la primera parte de la creación de la cuenta, para el envío de mensajes de servicio, de información requerida, y de algunos eventos y productos. Además, si un usuario requiere su contraseña, esta es enviada en texto a la dirección de e-mail registrada. País, Trabajo y Puesto, e Industria sólo son utilizados para mejorar nuestro conocimiento de nuestra audiencia y mejorar la experiencia del usuario y nunca en casos individuales. Subscripciones Online y subscripciones a Eventos requiere información adicional, como número de tarjeta de crédito y dirección de facturación. Esta información se utiliza para la facturación y para procesar la orden. En el caso de que tengamos inconvenientes procesando la orden, esta información de contacto será para contactar al usuario y resolver el problema. Enviamos a todos nuestros miembros recientes un e-mail de bienvenida para verificar contraseña y nombre de usuario. Miembros más antiguos recibirán información ocasionalmente sobre nuestros productos, Servicios y ofertas especiales.</li>
                <li><strong>Encuestas y Concursos:</strong> De vez en cuando, nuestra página pedirá información a nuestros usuarios a través de encuestas y concursos. La participación en ellos es completamente voluntaria y por lo tanto, el usuario tiene la opción de enviar esa información o no. La información solicitada puede incluir información de contacto (como nombre y dirección), opinión personal e información demográfica (como código postal, rango de edad, preferencias de compra). La información de contacto será utilizada para notificar a los ganadores. La información de la encuesta será utilizada con el propósito de monitorizar o mejorar la utilización del sitio. Esta información podría ser compartida con nuestros socios. En el caso de que el manejo de información de una encuesta en específico difiera de lo que se describe en esta política de privacidad, esas diferencias serán claramente marcadas y resaltadas en la introducción de la encuesta.</li>
                <li><strong>Seguir el Tráfico:</strong> Actualmente tenemos un contrato con Omniture para medir nuestras estadísticas de tráfico. Utilizamos estos servicios para medir cómo los usuarios usan nuestra página. Para hacerlo, utilizamos cookies provistas por Omniture en esta página. El tipo de información que recolectamos incluye unique visitors, page views, puntos de entrada y de salida, y una variedad de otra información agregada. Al suplementar nuestra información, esa información nos ayuda a conocer cosas como qué páginas son más atractivas para nuestros visitantes, cuál de nuestro producto le interesa más a nuestros clientes y qué tipo de ofertas quieren ver nuestros clientes. Aunque Omniture obtiene la información de nuestra página, nosotros controlamos cómo se utiliza la información.</li>
            </ol>

            <h2>Cómo utilizamos esta información</h2>
            <ol>
                <li><strong>Compartir:</strong> Periódicamente compartimos información demográfica del conjunto con nuestros consejeros. Utilizamos empresas ajenas para construir servicios y productos. Estas empresas no retienen, comparten, almacenan ni usan información personal para ningún propósito secundario.</li>
                <li><strong>Publicar:</strong> Todos los comentarios colgados a artículos o a blogs aparecerán inmediatamente online, junto al nombre de usuario que el usuario ha designado. Technology Review eliminará comentarios ilegales o inapropiados.</li>
            </ol>

            <h2>Cómo Terceras Partes, Sitios, y Patrocinadores Utilizan esta Información</h2>
            <p><strong>Publicidad de terceros:</strong> Utilizamos DART y otras empresas de publicidad para montar anuncios en nuestra web. Estas compañías podrían utilizar tu información (sin incluir tu nombre, dirección, correo electrónico número telefónico) de tus visitas a esta u otras páginas web para proveer publicidad en esta página y otras sobre productos y servicios que pudieran resultar interesantes para ti. Si desea más información sobre esta práctica, y sobre su opción de que estas empresas utilicen esta información, por favor haga click aquí.</p>
            <ol>
                <li><strong>Cookies de Terceros:</strong> Al proveer de publicidad a esta página, nuestro publicista podrá reconocer o ubicar una única “cookie” en tu buscador.</li>
                <li><strong>Distribución del Vendedor:</strong> Technology Review podrá divulgar información de los usuarios a terceros que han acordado proveer servicios a Technology Review y quienes han acordado mantener confidencialidad de esa información como se acuerda en la Política de Privacidad. Estas empresas proveerán a Technology Review con una variedad de servicios incluyendo, y sin limitaciones, procesamiento y almacenamiento de información de usuarios, ayudando a crear nuevo contenido y promociones para la página de Technology Review, y enviar o coordinar comunicaciones de marketing que los usuarios han aceptado a recibir. Technology Review mostrará información individual de usuarios a autoridades gubernamentales o judiciales, o a cualquier otra entidad en respuesta citación, orden judicial o algún otro procedimiento judicial. En cuestiones referidas a la seguridad personal o pública, Technology Review podría proveer información voluntariamente a autoridades gubernamentales competentes.</li>
            </ol>

            <h2>Opciones de Privacidad del Usuario</h2>
            <ol>
                <li><strong>Corregir/Actualizar Información Personal:</strong> Si cambia la información del usuario que es identificable personalmente (tal como un código postal), o si un usuario ya no desea un servicio, ofrecemos un modo para corregir, actualizar o quitar esos datos personales del usuario. Eso es en la página de Mi Cuenta a la cual se puede acceder ingresando aquí: http://my.technologyreview.com/es/mytr/login.aspx</li>
                <li><strong>Opción -salir:</strong> Los usuarios que ya no quieran recibir nuestro Boletín de Noticias pueden cancelar la suscripción en la página de Mi Cuenta a la cual se puede acceder ingresando aquí: http://my.technologyreview.com/es/mytr/login.aspx.</li>
                <li><strong>Actualizaciones de la Página y del Servicio:</strong> A nuestros usuarios les enviamos anuncios del servicio y de la página por correo electrónico. Los miembros se suscriben automáticamente a estos anuncios del servicio, que contienen información importante respecto de la página, el registro del usuario, o de un servicio al cual se suscribió.</li>
            </ol>

            <h2>Privacidad de los Niños</h2>
            <p>La ley The Children’s Online Privacy Protection Act (COPPA), aprobada por el Congreso en octubre de 1998, exige que la Comisión de Comercio Nacional (FTC) emita y haga cumplir la reglamentación referida a la privacidad online de los niños. La FTC emitió la reglamentación Children’s Online Privacy Protection Rule en noviembre 1999; que está en vigencia desde el 21 de abril de 2000. La meta primaria de la reglamentación es que los padres controlen la información que recogen sus hijos online.</p>
            <p>Si bien Technology Review no está comprendida por las pautas a las cuales deben adherirse las páginas que sí deben adherirse a COPPA, si los padres nos informan que sus niños le brindan a la empresa información personal, la empresa anulará dichos archivos en un lapso de tiempo razonable.</p>

            <h2>Compromiso con la Seguridad</h2>
            <p>Tomamos todas las precauciones para proteger la información de nuestros usuarios. Cuando un usuario remite información confidencial a través de la página, la información está protegida tanto online como offline. Cuando nuestro formulario de registración/pedido le solicita a los usuarios que ingresen información confidencial (tal como número de tarjeta de crédito), se codifica y protege a través del software de codificación de SSL. Toda la información de nuestros usuarios, no solo la información confidencial antedicha se restringe a nuestras oficinas. Únicamente los empleados que necesitan la información para realizar una tarea específica (por ejemplo un representante de servicios al cliente) tiene acceso a información identificable del cliente. A todos los empleados se los actualiza respecto de nuestras practicas de seguridad y privacidad. Por último, los servidores en que almacenamos la información personal identificable, se guardan en un lugar blindado. Si tiene preguntas respecto de la seguridad en nuestra página, envíenlas a customerservice@technologyreview.com.</p>
        </LegalLayout>
    );
}
