import * as admin from 'firebase-admin';
import * as fs from 'fs';
import * as path from 'path';

if (process.env.FIRESTORE_EMULATOR_HOST) {
    console.log("Connecting to Firestore Emulator...");
    admin.initializeApp({ projectId: "demo-project" });
} else {
    // Load service account (for production)
    const serviceAccountPath = path.join(process.cwd(), 'service-account.json');

    if (!fs.existsSync(serviceAccountPath)) {
        console.error('Error: service-account.json not found in the root directory.');
        console.error('Please download it from Firebase Console > Project Settings > Service Accounts.');
        process.exit(1);
    }

    const serviceAccount = require(serviceAccountPath);

    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
    });
}

const db = admin.firestore();

function slugify(text: string): string {
    return text.toString().toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')    // Replace all non-word chars with -
        .replace(/\-\-+/g, '-')         // Replace multiple - with single -
        .replace(/^-+/, '')             // Trim - from start of text
        .replace(/-+$/, '');            // Trim - from end of text
}

// Function to check if a document ID looks like a Firebase auto-generated push ID (20 chars, alphanumeric)
function isAutoGeneratedId(id: string): boolean {
    return /^[a-zA-Z0-9]{20}$/.test(id);
}

async function migrate() {
    console.log('Starting migration of article URLs (Firestore Document IDs)...');

    try {
        // Only get the 13 most recently published articles (these will be the ones ingested via API)
        const articlesSnapshot = await db.collection('articles')
            .orderBy('publishedAt', 'desc')
            .limit(13)
            .get();
        console.log(`Found ${articlesSnapshot.size} recent articles to process.`);

        let migratedCount = 0;

        for (const doc of articlesSnapshot.docs) {
            const currentId = doc.id;
            const articleData = doc.data();

            // Only migrate if it looks like an auto-generated random string instead of a slug
            if (isAutoGeneratedId(currentId) && articleData.title) {
                console.log(`Migrating article ID [${currentId}] - Title: "${articleData.title}"`);

                let baseSlug = slugify(articleData.title);
                if (!baseSlug) {
                    baseSlug = 'article'; // Fallback layout
                }

                // Check for collisions for the new slug ID
                let newUniqueId = baseSlug;
                let counter = 1;

                let checkDoc = await db.collection('articles').doc(newUniqueId).get();
                while (checkDoc.exists) {
                    // Check if the one that exists is actually the one we just migrated previously
                    newUniqueId = `${baseSlug}-${counter}`;
                    counter++;
                    checkDoc = await db.collection('articles').doc(newUniqueId).get();
                }

                // 1. Create the new document with the slug ID
                await db.collection('articles').doc(newUniqueId).set(articleData);
                console.log(` > Created new document: ${newUniqueId}`);

                // 2. Update any related entities referencing the old document ID
                await updateRelatedReferences(currentId, newUniqueId);

                // 3. Delete the old document
                await db.collection('articles').doc(currentId).delete();
                console.log(` > Deleted old document: ${currentId}`);

                migratedCount++;
            }
        }

        console.log(`\nMigration complete! Successfully migrated ${migratedCount} articles to slug-based IDs.`);

    } catch (error) {
        console.error('Migration failed with error:', error);
    }
}

async function updateRelatedReferences(oldId: string, newId: string) {
    // 1. Update references in "collections"
    const collectionsRef = db.collection('collections');
    const collectionsSnapshot = await collectionsRef.get();

    for (const collDoc of collectionsSnapshot.docs) {
        const data = collDoc.data();
        if (data.articleIds && data.articleIds.includes(oldId)) {
            // Replace oldId with newId while preserving order
            const updatedArticleIds = data.articleIds.map((id: string) => id === oldId ? newId : id);
            await collectionsRef.doc(collDoc.id).update({ articleIds: updatedArticleIds });
            console.log(`   * Updated reference in collection '${collDoc.id}' (${data.title})`);
        }
    }

    // 2. Update references in "informes"
    const informesRef = db.collection('informes');
    const informesSnapshot = await informesRef.get();

    for (const infoDoc of informesSnapshot.docs) {
        const data = infoDoc.data();
        if (data.articleIds && data.articleIds.includes(oldId)) {
            // Replace oldId with newId while preserving order
            const updatedArticleIds = data.articleIds.map((id: string) => id === oldId ? newId : id);
            await informesRef.doc(infoDoc.id).update({ articleIds: updatedArticleIds });
            console.log(`   * Updated reference in informe '${infoDoc.id}' (${data.title})`);
        }
    }
}

migrate().then(() => {
    process.exit(0);
});
